name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
          cache: "npm"
      - name: Install dependencies
        run: npm i
      - name: Lint
        run: npm run lint